project_id = "jndkoglwwubglslojdic"

[functions.analyze-signal]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.ingest-signals]
verify_jwt = false

[functions.lingua-fidelity]
verify_jwt = false
